### ISSUE TITLE
[FEAT] MageCheck Store Validation Workflow

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/magecheck#1]
# :bulb: Feature request

## Feature Name
MageCheck (Store)

## The Desired Behavior

I would like a workflow that does the following:

- [ ] Varnish Compatibility
- [ ] Cypress Tests from Elegentos
- [ ] MFTF Core Subset Tests
- [ ] MFTF Tests (for the store)
- [ ] Unit Tests (for the store)
- [ ] Integration Tests (for the store)
- [ ] [Coding Standard](https://github.com/graycoreio/github-actions-magento2/tree/main/coding-standard)
- [ ] [Quality Health Checks from Run as Root](https://github.com/run-as-root/gitlab-pipeline-templates/blob/master/static/phpmetrics.yaml#L17)
- [ ] Performance Test
- [ ] `classmap-authoritative` compliance
- [ ] `di:compile` compliance

across the following constraints

- [ ] `MAGE_MODE` as `developer` and `production`

The API for usage of this workflow should look something like below and should be as simple as possible to use. 

**This is primarily for the new dev looking to get started out of the box, this action needs to be a good first step.  We can always support more complex configuration,**

Each of these individual features can be implemented as a individual feature that people can use to make their own workflows, as well. 

```yml
name: MageCheck (store)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  magecheck:
    uses: graycoreio/github-actions-magento2/.github/workflows/magecheck.yaml@main
    secrets:
      composer_auth: ${{ secrets.COMPOSER_AUTH }}
```

## Your Use Case
As a developer, I want to create provably high-quality stores on Github.

## Prior Work

cc: @vbuck @DavidLambauer @peterjaap @Vinai
